# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dc158d4db8c5a0d442d3c33dcfa6fd91445ea6ade518c53b37e0f8ba21bba0a7ddd5b66f21e9c07dc9c44b6490cbabaeb15c039c10eb34f32523b53bf44fa5f
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_CLIENT_SECRET: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

test:
  secret_key_base: 997fbe0b5c6680144a03277ec7803175f0ebbb7d0a2b877c87de04500bda485d7e552a2dbe7dc8cb1c2b95658fdee4fc9f07d3fe66be3d41cd2bc5c062e8bd70
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_CLIENT_SECRET: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_CLIENT_SECRET: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
